default:
  image: tkf2023/env:rcore-ci

stages:
  - test

test-code-job:
  stage: test
  script:
    - git clone https://token:${rCoreCheckToken}@git.tsinghua.edu.cn/os-lab/2025S/ta/rcore-tutorial-checker-2025S.git ci-user
    - git clone https://token:${rCoreTestToken}@git.tsinghua.edu.cn/os-lab/2025S/public/rcore-tutorial-test-2025S.git ci-user/user
    - cd ci-user && make test CHAPTER=`echo $CI_COMMIT_REF_NAME | grep -oP 'ch\K[0-9]'` passwd=$BASE_TEST_TOKEN OFFLINE=1
