[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Cforce-frame-pointers=yes",
    '--cfg=board="qemu"',
]

[source]
crates-io = { replace-with = "vendored-sources" }

[source.vendored-sources]
directory = "vendor"